### ISSUE TITLE
kinetic_scheme documentation: minus sign missing in gaussian exponent

### ISSUE THREAD

**Issue by timvanderzee** [Campbell-Muscle-Lab/FiberSim#109]
In the transitions part of the kinetic_scheme documentation (https://campbell-muscle-lab.github.io/FiberSim/pages/structures/kinetic_scheme/kinetic_scheme.html), a minus sign is missing in the exponent of the gaussian. It says that if b is not defined, it is set equal to 1. This is indeed done in code, but then the exponent would always be positive. In code, there is a minus sign that is not shown in the documentation.

**Comment by utkugulbulak** [comment]
@timvanderzee - Thank you so much for bringing this to our attention. The documentation is updated.
