### ISSUE TITLE
Test the dumped force equals the averaged force across the thick filaments

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#17]
# Description

We need to validate that the dumped half-sarcomere force is within an error tolerance range of the average force on the last node of the thick filaments.

I've already written the code to calculate this force in the internodal force balances that I've done previously, so it will be a matter of refactoring this and testing that it decreases with dump precision.

**Comment by Sarah-Kst** [comment]
Force balance checking algorithm implemented in commit 1e2ef0c1c83101e40fbe1898622e04235f813763.
