### ISSUE TITLE
Temporarily Offset C-Protein for Star Wars Animation

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#21]
# Description

Just for the Star Wars animation, we need to offset the C-protein from the cross-bridges since this is not yet implemented in the model. I'm creating a similar issue for actually implementing this in the core model and reversing this in the visualization.

**Comment by Sarah-Kst** [comment]
It is possible to specify the C-protein angle offset in the JSON model to have it further away from the CBs (see figure below - C-protein in pink and CB in blue).
![hs_401](https://user-images.githubusercontent.com/65904084/121575352-45ca7a00-c9f5-11eb-9ad2-62a80a83b091.png)
