### ISSUE TITLE
Investigate why there is a gap between 0 and -0.5 nanometers for the transition validation

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#26]
# Description

There's a strange gap in the detachment rate equation for cross-bridges at 0 and -0.5 nanometers. This is worth investigating since it seems to appear out of nowhere.

![rate_equation_2_isometric_fixed_stretch](https://user-images.githubusercontent.com/44296682/79248222-878b7f00-7e49-11ea-85d2-2136d5af2338.png)

**Comment by Sarah-Kst** [comment]
Solved by adding"lambda_jitter" option. Kinetics testing suite is now published on the github webpage.
