### ISSUE TITLE
Incorporate Angle Factor into Transition Validation

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#27]
# Description

Currently the angle factor is not incorporated into the cross-bridge transition validation. This leads to the transition validation routines to not validate like the following:

![rate_equation_1_isometric](https://user-images.githubusercontent.com/44296682/79248459-e0f3ae00-7e49-11ea-85aa-26daeef94852.png)

**Comment by Sarah-Kst** [comment]
Done in commit 1e2ef0c1c83101e40fbe1898622e04235f813763
