### ISSUE TITLE
Add simple check for camera array in top-level JSON

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#32]
# Description

I need to add a simple check for the camera JSON array in the top-level JSON to ensure that the array is containing objects of the right structure. It would be a pain to start constructing a geometry only to find out that the camera position wasn't valid and Blender to quit after it had started.

I already have the structure for checking parameters so this should be very quick to implement.

**Comment by Sarah-Kst** [comment]
Issue is no longer relevant since the whole visualization pipeline was updated (see commit b86ae513c25715bdfaf4850933e3d120acdd8136)
