### ISSUE TITLE
C-protein angle offset is smaller than specified

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#36]
# Description

The c-protein offset that is specified in the `BlenderParams` class isn't implemented as large as it is specified.

**Comment by Sarah-Kst** [comment]
Since @kenatcampbellmusclelab has re-written a big part of the visualization pipeline (see commit 70aaab75d117939c8117dddfc59e22e41f592fab), this issue is no longer relevant.
