### ISSUE TITLE
Potential bug in cross-bridge binding

### ISSUE THREAD

**Issue by dcolli23** [Campbell-Muscle-Lab/FiberSim#37]
# Description

There appears to be a bug in the cross-bridge binding to actin sites as demonstrated in the following picture taken from the Star Wars-inspired zoom through the half-sarcomere.

![model_1045](https://user-images.githubusercontent.com/44296682/80525848-dd8b1700-895f-11ea-97fa-7bca32ef4d20.png)

I believe this might be a result of not including a 'projection factor' like what was included in the old FiberSim model. This 'projection factor' accounted for distance from the binding site in the cross-bridge's probably to transition to a bound state.

**Comment by Sarah-Kst** [comment]
* Blender visualization is now operating
* Myosin kinetics algorithm has been tested and validated in commit 1e2ef0c1c83101e40fbe1898622e04235f813763
