### ISSUE TITLE
Muscle plan

### ISSUE THREAD

**Issue by kenatcampbellmusclelab** [Campbell-Muscle-Lab/FiberSim#6]
Muscle is updating p_hs->FiberSim_data from the muscle::implement_time_step function.

half-sarcomeres should update their own data records.

**Comment by Sarah-Kst** [comment]
@kenatcampbellmusclelab Since you re-organized the muscle and half-sarcomere class in commit 9f13b8653e89b861f88cf044849e86bdf5c79d0b, is this issue still relevant?
