### ISSUE TITLE
isAlive() method was renamed is_alive() in Python version 3.9

### ISSUE THREAD

**Issue by Sarah-Kst** [Campbell-Muscle-Lab/FiberSim#71]
A line from the batch.py code leads to an error if the user is working with the 3.9 (most recent) Python version. Line 85 should be replaced with "if not thread.is_alive()".

![run_batch](https://user-images.githubusercontent.com/65904084/117496654-59da1200-af45-11eb-9fee-2cfa890831d8.PNG)

@kenatcampbellmusclelab I use Python 3.8.5 and the code works with "is_alive()" instead of "IsAlive()", so I am planning to push a commit with the new line. I am creating this issue in case a similar problem occurs in the future for someone working with a different Python version.

**Comment by kenatcampbellmusclelab** [comment]
Done
