### ISSUE TITLE
Filament y - z calculation has to be generalized

### ISSUE THREAD

**Issue by kenatcampbellmusclelab** [Campbell-Muscle-Lab/FiberSim#8]
Need more solid code to calculate y and z positions for filaments on the fly. Currently only works for m_n = 9. Mirror code also needs to be generalized for nearest_actin_matrix.

**Comment by Sarah-Kst** [comment]
Updating this issue. Chandler and/or Ahkil will help me improve that part of the code.

**Comment by Sarah-Kst** [comment]
Chandler re-calculated the thin/thick filaments positions based on the C++ code and showed that an hexagonal lattice is obtained for even and odd m_n. values He also checked that each thin filament has 3 distinct nearest thick neighbors, and each thick filament has 6 nearest thin neighbors.

<img width="145" alt="m_n_9_with_thin" src="https://user-images.githubusercontent.com/65904084/126230448-13d6b0dd-5838-45ca-a7c3-dc8592d9f464.png">
<img width="184" alt="m_n_16_with_thin" src="https://user-images.githubusercontent.com/65904084/126230453-7cc8314c-81fe-4751-87cd-2da6fb08342d.png">

Jose ran single frame visualizations with Blender which also showed the regular hexagonal lattice for m_n = 16 and m_n = 25.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/65904084/126230704-cc575dde-e256-4ed9-a377-c3579c9d0941.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/65904084/126230710-1f2b2c96-99f0-42b5-83fc-1ed3856eb351.png)
