### ISSUE TITLE
Add module for generating force-velocity curves

### ISSUE THREAD

**Issue by Sarah-Kst** [Campbell-Muscle-Lab/FiberSim#86]
It would be practical to add a module in FiberPy that allows to automatically generate force-velocity curves, without having to specify the absolute load in the protocol files. 

Moving forward, it would be great to have a module that would generate tension-pCa/force-velocity/k_tr data for any input model file.

**Comment by Sarah-Kst** [comment]
Ken added a "characterize_model" module in FiberPy (see commit 178c3e0954bcd7b7e1f65990b5ccca4e44c60f80). Sarah will add a demo about this on the website.

**Comment by kenatcampbellmusclelab** [comment]
FiberPy completed but not documented
