### ISSUE TITLE
Improving half_sarcomere::myosin_kinetics function implementation

### ISSUE THREAD

**Issue by Sarah-Kst** [Campbell-Muscle-Lab/FiberSim#89]
Instead of looping over all the myosin heads, Ken suggested to use a double loop (over the hubs then over the dimers) with a "continue" statement if a SRX transition is involved with the dimer (because dimer heads transition together in and out of the SRX state).

![thick_kinetics](https://user-images.githubusercontent.com/65904084/159772916-7235efd6-f26c-495e-b717-cf0c0ab5eec4.PNG)

**Comment by kenatcampbellmusclelab** [comment]
Out of date
