### ISSUE TITLE
Demos now lead to slightly different results than with FiberSim1.2.0

### ISSUE THREAD

**Issue by Sarah-Kst** [Campbell-Muscle-Lab/FiberSim#93]
Ken noticed that the demos figures (like https://campbell-muscle-lab.github.io/FiberSim/pages/demos/getting_started/isometric_activation/isometric_activation.html) are slightly different than the one obtained with the last FiberSim version from this repo. There have been ~20 commits since the v1.2.0 release so it should be easy to track which modifications happened.

After this is fixed, it would be great to make sure that as we run the demos, the figures are saved in the /docs folder so the website is updated immediatly.

**Comment by kenatcampbellmusclelab** [comment]
Out of date
